### ISSUE TITLE
🐛 Bug - Queries missing connected users

### ISSUE THREAD

**Issue by joshbermanssw** [SSWConsulting/SSW.SophieBot#707] opened 2024-07-10 07:05 UTC
Cc:

Hi @AttackOnMorty 

### Describe the Bug

When I ask the prompt "Who is in the Sydney office today" i get less people than when i ask "who is in the Sydney office now". There should never be more people in 'NOW' than in 'TODAY'

![Image](https://github.com/SSWConsulting/SSW.SophieBot/assets/137844305/621340a6-d153-4e86-91af-94ae2515f882)

**Figure: 12 People in the office TODAY**

![Image](https://github.com/SSWConsulting/SSW.SophieBot/assets/137844305/42ab32c3-d20d-4153-9705-fb576656b70f)

**Figure: 19 People in the office NOW**

### To Reproduce
1. Prompt "Who is in the sydney office today"
2. Prompt "Who is in the sydney office now"

### Expected Behavior

The number of users in the office today is > than number of users in now. 
Both prompts are correctly fetching data 

```[tasklist]
### Tasks
- [ ] Investigate
- [ ] Fix
```

### Acceptance Criteria

- [ ] Meets [Definition of Done](../../_docs//Definition-of-Done.md)
- [ ] ...

### Environment
 - Device: [e.g. iPhone 12]
 - Browser: [e.g. chrome, safari]

### Screenshots

Thanks!

**Comment by AttackOnMorty** [comment] 2024-08-11 11:23
Duplicate of #667

**Closed by AttackOnMorty** 2024-08-11 11:23 UTC
Labels: Type: Bug
